#!/usr/bin/env bash
# Launches a PX4 SITL instance against the custom Gazebo world/model defined
# in px4-additions/ (see library/write_px4_with_px4_additions.sh to sync them
# into PX4-Autopilot first, and library/set_env.sh for the env vars used
# below).
#
# To reset the EKF origin manually after launch:
#   $PX4_DIR/build/px4_sitl_default/bin/px4-commander set_ekf_origin <lat> <lon> <alt>
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/library/set_env.sh"

require_dir "$PX4_DIR/build/px4_sitl_default" "Error: no PX4 SITL build found. Run scripts/build_px4.sh first."

# Adds worlds/models/plugins - including px4-additions/worlds/ once synced in
# - to GZ_SIM_RESOURCE_PATH. Generated by CMake at build time; it appends to
# GZ_SIM_RESOURCE_PATH/GZ_SIM_SYSTEM_PLUGIN_PATH without checking they're
# already set, which trips `set -u` on a fresh shell.
export GZ_SIM_RESOURCE_PATH="${GZ_SIM_RESOURCE_PATH:-}"
export GZ_SIM_SYSTEM_PLUGIN_PATH="${GZ_SIM_SYSTEM_PLUGIN_PATH:-}"
source "$PX4_DIR/build/px4_sitl_default/rootfs/gz_env.sh"

echo "[*] Killing any leftover Gazebo/PX4 processes..."
"$SCRIPT_DIR/library/kill_gazebo.sh"

READY_STRING="Ready for takeoff!"

launch_px4() {
    local instance=$1
    local autostart=$2
    local model=$3
    local pose=${4:-}
    local logfile="/tmp/px4_instance_${instance}.log"
    local pidfile="/tmp/px4_instance_${instance}.pid"

    echo "[*] Launching PX4 instance $instance (model=$model, autostart=$autostart)..."

    # -d disables px4's interactive "pxh>" shell. Without it, px4's getchar()
    # read loop never blocks once stdin isn't a real controlling terminal (as
    # here, backgrounded from a script) - it spins re-printing the prompt as
    # fast as the CPU allows, pegging a core and growing $logfile without
    # bound instead of settling down after startup.

    # setsid puts px4 (and the gz sim server/gui it spawns as direct
    # children) in a new session/process group, so library/kill_gazebo.sh
    # can kill exactly this tree via its PGID instead of pattern-matching
    # process names system-wide. `$!` after `setsid cmd &` is unreliable -
    # setsid forks internally and $! can end up pointing at an
    # already-exited intermediate - so the pidfile is written from inside
    # the process that actually execs into px4, guaranteeing it's correct.
    rm -f "$pidfile"
    setsid bash -c 'echo $$ > "$1"; shift; exec "$@"' _ "$pidfile" \
        env PX4_HOME_LAT="$PX4_HOME_LAT" \
            PX4_HOME_LON="$PX4_HOME_LON" \
            PX4_HOME_ALT="$PX4_HOME_ALT" \
            PX4_GZ_WORLD="$PX4_GZ_WORLD" \
            PX4_SYS_AUTOSTART="$autostart" \
            PX4_SIM_MODEL="$model" \
            PX4_GZ_MODEL_POSE="$pose" \
            "$PX4_DIR/build/px4_sitl_default/bin/px4" -i "$instance" -d \
        < /dev/null > "$logfile" 2>&1 &
    disown

    # Wait for the pidfile write, not a fixed sleep - it lands within a
    # syscall or two of setsid's fork, so this is normally instant.
    for _ in $(seq 1 50); do
        [[ -s "$pidfile" ]] && break
        sleep 0.1
    done

    echo "PID: $(cat "$pidfile" 2>/dev/null || echo "unknown - check $pidfile")"
}

wait_for_ready() {
    local instance=$1
    local logfile="/tmp/px4_instance_${instance}.log"
    local timeout=30  # seconds
    local elapsed=0

    echo "[*] Waiting for instance $instance to be ready..."

    while (( elapsed < timeout )); do
        if grep -q "$READY_STRING" "$logfile" 2>/dev/null; then
            echo "[+] Instance $instance is ready!"
            return 0
        fi
        sleep 1
        elapsed=$((elapsed + 1))
    done

    echo "[!] Timeout waiting for instance $instance. Check $logfile" >&2
    return 1
}

# --- Launch sequence ---

# Matches PX4's own gz_<model>_<world> make target's WORKING_DIRECTORY, so
# dataman/logs/etc. land in the same place a `make` launch would put them.
cd "$PX4_DIR/build/px4_sitl_default/rootfs"

launch_px4 0 "$PX4_SYS_AUTOSTART" "$PX4_SIM_MODEL" "$PX4_GZ_MODEL_POSE"
wait_for_ready 0

echo "[+] Gazebo simulation is ready! Ctrl-C to stop."

# px4 runs in its own session (via setsid in launch_px4), so it's no longer
# a child of this shell - Ctrl-C here won't reach it on its own, and a bare
# `wait` would return immediately instead of blocking on it. Trap the
# interrupt and clean up explicitly instead.
trap '"$SCRIPT_DIR/library/kill_gazebo.sh"; exit 0' INT TERM

while kill -0 "-$(cat /tmp/px4_instance_0.pid 2>/dev/null)" 2>/dev/null; do
    sleep 1
done
echo "[!] PX4 instance 0 exited unexpectedly. Check /tmp/px4_instance_0.log" >&2
exit 1
